---
# handlers file for base
  - name: Restart systemd-resolved
    systemd:
      state: restarted
      enabled: yes
      daemon_reload: yes
      name: "systemd-resolved"

  - name: Restart fail2ban
    systemd:
      state: restarted
      enabled: yes
      daemon_reload: yes
      name: "fail2ban"

  - name: Restart nftables
    systemd:
      state: restarted
      enabled: yes
      daemon_reload: yes
      name: "nftables"

  - name: Disable ufw
    systemd:
      state: stopped
      enabled: no
      daemon_reload: yes
      masked: yes
      name: "ufw"
